import { StyleSheet } from "react-native";

export const formStyles = StyleSheet.create({
  // Form Group
  formGroup: {
    marginTop: 24,
  },
  formLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#8E8E93",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1C1C1E",
    marginBottom: 8,
    letterSpacing: 0.3,
  },

  hide: {
    display: "none",
  },
  formLabelInline: {
    fontSize: 13,
    fontWeight: "600",
    color: "#8E8E93",
    letterSpacing: 0.5,
    marginLeft: 8,
  },
  formInput: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 16,
    fontSize: 17,
    color: "#000000",
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },

  // Notes Preview Card
  notesPreviewCard: {
    backgroundColor: "#FFFEF7",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#F0EDD4",
    padding: 16,
    minHeight: 100,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  notesPreviewContent: {
    flex: 1,
  },
  notesPreviewText: {
    fontSize: 15,
    color: "#3C3C3C",
    lineHeight: 22,
    marginBottom: 12,
  },
  notesPreviewFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F0EDD4",
  },
  notesPreviewMeta: {
    fontSize: 12,
    color: "#8E8E93",
  },
  notesEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
  },
  notesEmptyText: {
    fontSize: 15,
    color: "#C7C7CC",
    marginTop: 8,
  },

  // // Date Picker
  // datePickerBtn: {
  //   flexDirection: "row",
  //   alignItems: "center",
  //   backgroundColor: "#FFFFFF",
  //   borderRadius: 10,
  //   padding: 16,
  //   borderWidth: 1,
  //   borderColor: "#E5E5EA",
  //   shadowColor: "#000",
  //   shadowOffset: { width: 0, height: 1 },
  //   shadowOpacity: 0.05,
  //   shadowRadius: 2,
  //   elevation: 1,
  // },
  // datePickerText: {
  //   fontSize: 17,
  //   color: "#000000",
  //   marginLeft: 12,
  //   flex: 1,
  // },

  // Subtask Input
  subtaskInputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingLeft: 16,
    paddingRight: 8,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  subtaskInput: {
    flex: 1,
    fontSize: 17,
    color: "#000000",
    paddingVertical: 12,
  },
  addSubtaskBtn: {
    padding: 4,
  },
  subtaskPreview: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  subtaskPreviewText: {
    flex: 1,
    fontSize: 15,
    color: "#000000",
    marginLeft: 12,
  },

  // Reminder Styles
  reminderHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  reminderLabelRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  reminderSettings: {
    backgroundColor: "#F9F9F9",
    borderRadius: 10,
    padding: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#E5E5EA",
  },
  reminderSectionLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 12,
  },
  reminderDaysRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  reminderDayBtn: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E5EA",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  reminderSectionCaption: {
    fontSize: 12,
    color: "#555",
    opacity: 0.7,
    marginTop: -4,
    marginBottom: 12,
  },

  reminderDayBtnActive: {
    backgroundColor: "#007AFF",
    borderColor: "#007AFF",
    shadowColor: "#007AFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  reminderDayText: {
    fontSize: 11,
    color: "#000000",
    fontWeight: "500",
  },
  reminderDayTextActive: {
    color: "#FFFFFF",
    fontWeight: "600",
  },

  customDaysContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginTop: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  customDaysLabel: {
    fontSize: 15,
    color: "#374151",
    fontWeight: "500",
    marginBottom: 12,
    letterSpacing: 0.2,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
  },
  customDaysInput: {
    width: 70,
    height: 44,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 18,
    fontWeight: "700",
    color: "#1F2937",
    textAlign: "center",
    borderWidth: 1.5,
    borderColor: "#D1D5DB",
    marginRight: 10,
  },
  customDaysUnit: {
    fontSize: 15,
    color: "#6B7280",
    fontWeight: "500",
    letterSpacing: 0.3,
  },
  reminderHint: {
    fontSize: 13,
    color: "#8E8E93",
    marginTop: 12,
    lineHeight: 18,
    backgroundColor: "#F0F7FF",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#007AFF",
  },
  timePickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  timePickerText: {
    flex: 1,
    fontSize: 17,
    color: "#000000",
    marginLeft: 12,
    fontWeight: "600",
  },
  timePickerChevron: {
    marginLeft: 8,
  },

  // Category Selector
  categorySelectorRow: {
    flexDirection: "row",
    gap: 8,
  },
  categoryOptionBtn: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 14,
    borderWidth: 2,
    borderColor: "#E5E5EA",
    gap: 6,
  },
  categoryOptionBtnActive: {
    borderColor: "#007AFF",
    backgroundColor: "#F0F7FF",
  },
  categoryOptionIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  categoryOptionIconTugas: {
    backgroundColor: "#E3F2FD",
  },
  categoryOptionIconJadwal: {
    backgroundColor: "#FFF3E0",
  },
  categoryOptionIconKegiatan: {
    backgroundColor: "#F3E5F5",
  },
  categoryOptionText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#8E8E93",
  },
  categoryOptionTextActive: {
    color: "#007AFF",
  },

  // Repeat Options
  repeatOptionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  repeatOptionBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#F2F2F7",
    borderWidth: 2,
    borderColor: "#E5E5EA",
  },
  repeatOptionBtnActive: {
    backgroundColor: "#007AFF",
    borderColor: "#007AFF",
  },
  repeatOptionText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#007AFF",
  },
  repeatOptionTextActive: {
    color: "#FFFFFF",
  },

  // Reminder Frequency
  reminderFrequencyRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  reminderFrequencyBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E5EA",
  },
  reminderFrequencyBtnActive: {
    backgroundColor: "#007AFF",
    borderColor: "#007AFF",
  },
  reminderFrequencyText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#8E8E93",
  },
  reminderFrequencyTextActive: {
    color: "#FFFFFF",
  },
  // Tambahkan ke formStyles
  customIntervalContainer: {
    marginTop: 16,
  },
  customIntervalRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 8,
  },
  customIntervalInput: {
    width: 60,
    height: 40,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    textAlign: "center",
  },
  customUnitPicker: {
    flexDirection: "row",
    flex: 1,
    gap: 8,
  },
  unitBtn: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#007AFF",
    borderRadius: 8,
    alignItems: "center",
  },
  unitBtnActive: {
    backgroundColor: "#007AFF",
  },
  unitBtnText: {
    fontSize: 14,
    color: "#007AFF",
  },
  unitBtnTextActive: {
    color: "#FFFFFF",
  },
  endOptionsContainer: {
    marginTop: 16,
  },
  endOptionsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  endOptionBtn: {
    flex: 1,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    borderRadius: 8,
    alignItems: "center",
  },
  endOptionBtnActive: {
    backgroundColor: "#007AFF",
    borderColor: "#007AFF",
  },
  endOptionText: {
    fontSize: 14,
    color: "#666",
  },
  endOptionTextActive: {
    color: "#FFFFFF",
  },
  endDateContainer: {
    marginTop: 12,
  },
  datePickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    borderRadius: 8,
  },
  datePickerText: {
    fontSize: 16,
    color: "#000",
  },
});
