import { StyleSheet } from "react-native";

export const formStyles = StyleSheet.create({
  // Form Group
  formGroup: {
    marginTop: 24,
  },
  formLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#8E8E93",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  formLabelInline: {
    fontSize: 13,
    fontWeight: "600",
    color: "#8E8E93",
    letterSpacing: 0.5,
    marginLeft: 8,
  },
  formInput: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 16,
    fontSize: 17,
    color: "#000000",
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },

  // Notes Preview Card
  notesPreviewCard: {
    backgroundColor: "#FFFEF7",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#F0EDD4",
    padding: 16,
    minHeight: 100,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  notesPreviewContent: {
    flex: 1,
  },
  notesPreviewText: {
    fontSize: 15,
    color: "#3C3C3C",
    lineHeight: 22,
    marginBottom: 12,
  },
  notesPreviewFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F0EDD4",
  },
  notesPreviewMeta: {
    fontSize: 12,
    color: "#8E8E93",
  },
  notesEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
  },
  notesEmptyText: {
    fontSize: 15,
    color: "#C7C7CC",
    marginTop: 8,
  },

  // Date Picker
  datePickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  datePickerText: {
    fontSize: 17,
    color: "#000000",
    marginLeft: 12,
    flex: 1,
  },

  // Subtask Input
  subtaskInputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingLeft: 16,
    paddingRight: 8,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  subtaskInput: {
    flex: 1,
    fontSize: 17,
    color: "#000000",
    paddingVertical: 12,
  },
  addSubtaskBtn: {
    padding: 4,
  },
  subtaskPreview: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  subtaskPreviewText: {
    flex: 1,
    fontSize: 15,
    color: "#000000",
    marginLeft: 12,
  },

  // Reminder Styles
  reminderHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  reminderLabelRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  reminderSettings: {
    backgroundColor: "#F9F9F9",
    borderRadius: 10,
    padding: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#E5E5EA",
  },
  reminderSectionLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 12,
  },
  reminderDaysRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  reminderDayBtn: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E5EA",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  reminderDayBtnActive: {
    backgroundColor: "#007AFF",
    borderColor: "#007AFF",
    shadowColor: "#007AFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  reminderDayText: {
    fontSize: 13,
    color: "#000000",
    fontWeight: "500",
  },
  reminderDayTextActive: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  customDaysContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    marginTop: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  customDaysLabel: {
    fontSize: 14,
    color: "#8E8E93",
    marginRight: 8,
  },
  customDaysInput: {
    width: 60,
    height: 40,
    backgroundColor: "#F2F2F7",
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    fontWeight: "600",
    color: "#000000",
    textAlign: "center",
    marginHorizontal: 8,
    borderWidth: 1,
    borderColor: "#E5E5EA",
  },
  customDaysUnit: {
    fontSize: 14,
    color: "#000000",
  },
  reminderHint: {
    fontSize: 13,
    color: "#8E8E93",
    marginTop: 12,
    lineHeight: 18,
    backgroundColor: "#F0F7FF",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#007AFF",
  },
  timePickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E5EA",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  timePickerText: {
    flex: 1,
    fontSize: 17,
    color: "#000000",
    marginLeft: 12,
    fontWeight: "600",
  },
  timePickerChevron: {
    marginLeft: 8,
  },
});